---
stages:
- build
- test
- deploy
include:
- remote: https://gitlab.com/gitlab-org/incubation-engineering/five-minute-production/library/-/raw/main/gcp/cloud-run.gitlab-ci.yml

deploy-to-cloud-run:
  after_script:
    - echo "$GCP_SERVICE_ACCOUNT_KEY" | jq --raw-output '.privateKeyData'>BLAH || exit 1
    - echo $?
    # - echo "$GCP_SERVICE_ACCOUNT_KEY"
    # - echo "$GCP_SERVICE_ACCOUNT_KEY" | jq --raw-output '.private_key_data'
    # - echo "$GCP_SERVICE_ACCOUNT_KEY" | jq --raw-output '.private_key_data' >local-service-account-key-file.json
    # - chmod o+rx local-service-account-key-file.json
    # - ls -al
    # - cat local-service-account-key-file.json
    # tt
default:
  tags: [saas-linux-large-amd64]
