stages:
  - build
  - gitops

# Build and push Docker image using Kaniko
build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE/main:$CI_COMMIT_SHA
  artifacts:
    paths:
      - updated-image-tag
    expire_in: 1 hour
  only:
    - main

# Generate and commit Kubernetes manifests using Kustomize
commit-manifests:
  stage: gitops
  image: docker:latest
  variables:
    KUSTOMIZE_BASE_PATH: "manifests/base"
  services:
    - docker:dind
  before_script:
    - apk add --no-cache git
    - echo "registry.gitlab.com/adess-demos/demo/app-team/catweb-gitops/main:$CI_COMMIT_SHA" > updated-image-tag
  script:
    - docker run --rm -v $(pwd):/workspace -w /workspace kubernetes/kustomize:v4.1.3 create -o $KUSTOMIZE_BASE_PATH --resources $KUSTOMIZE_BASE_PATH
    - docker run --rm -v $(pwd):/workspace -w /workspace kubernetes/kustomize:v4.1.3 edit set image app=registry.gitlab.com/adess-demos/demo/app-team/catweb-gitops/main:$CI_COMMIT_SHA --filename $KUSTOMIZE_BASE_PATH/kustomization.yaml
    - git config user.email "gitlab-ci@example.com"
    - git config user.name "GitLab CI"
    - git add .
    - git commit -m "Update Kustomize manifests with new image tag"
    - git push https://${GITLAB_USER}:${GITLAB_TOKEN}@gitlab.com/${CI_PROJECT_PATH}.git HEAD:main
  only:
    - main
