---
stages:
  - build
  - gitops
  - deploy
  - review
build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint:
      - ""
  script:
    - echo
      "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}"
      > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile
      $CI_PROJECT_DIR/Dockerfile --destination
      $CI_REGISTRY_IMAGE/main:$CI_COMMIT_SHA
  artifacts:
    paths:
      - updated-image-tag
    expire_in: 1 hour
  only:
    - main
    - merge_requests
commit-manifests:
  stage: gitops
  image:
    name: docker:latest
    entrypoint:
      - ""
  before_script:
    - apk add --no-cache curl git bash
    - curl -s
      "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"
      | bash
    - mv kustomize /usr/local/bin/
    - echo
      "registry.gitlab.com/adess-demos/demo/app-team/catweb-gitops/main:$CI_COMMIT_SHA"
      > updated-image-tag
    - git config --global user.email "adess@gitlab.com"
    - git config --global user.name
      "@project_44576698_bot_350adb3254374f09f5512b067abc866b"
  script:
    - cd manifests
    - git remote add gitlab_origin
      "https://oauth2:${CI_ACCESS_TOKEN}@gitlab.com/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}.git"
    - kustomize edit set image
      registry.gitlab.com/adess-demos/demo/app-team/catweb-gitops=registry.gitlab.com/adess-demos/demo/app-team/catweb-gitops:"$(cat
      ../updated-image-tag)"
    - kustomize build . > prod/k8s-deployment.yaml
    - cat k8s-deployment.yaml
    - git add *
    - git commit -m "Update Kubernetes manifests with new image tag"
    - git push gitlab_origin HEAD:main -o ci.skip
  only:
    - main
deploy_prod:
  stage: deploy
  script:
    - echo "Deployed manifests only for Environment creation"
  environment:
    name: prod
    url: https://prod.catweb.gitops.fun
  only:
    - main


review_deploy:
  stage: review
  image:
    name: docker:latest
    entrypoint:
      - ""
  before_script:
    - apk add --no-cache curl git bash
    - curl -s
      "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"
      | bash
    - mv kustomize /usr/local/bin/
    - echo
      "registry.gitlab.com/adess-demos/demo/app-team/catweb-gitops/main:$CI_COMMIT_SHA"
      > updated-image-tag
    - git config --global user.email "adess@gitlab.com"
    - git config --global user.name
      "@project_44576698_bot_350adb3254374f09f5512b067abc866b"
  script:
    - cd manifests
    - git remote add gitlab_origin
      "https://oauth2:${CI_ACCESS_TOKEN}@gitlab.com/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}.git"
    - kustomize edit set image
      registry.gitlab.com/adess-demos/demo/app-team/catweb-gitops=registry.gitlab.com/adess-demos/demo/app-team/catweb-gitops:"$(cat
      ../updated-image-tag)"
    - kustomize edit set namespace review-${CI_COMMIT_REF_SLUG}
    - kustomize edit set host review-${CI_COMMIT_REF_SLUG}catweb.gitops.fun  
    - mkdir -p review/$CI_COMMIT_REF_SLUG
    - kustomize build . > review/$CI_COMMIT_REF_SLUG/k8s-deployment.yaml
    - git add review/$CI_COMMIT_REF_SLUG/k8s-deployment.yaml
    - git commit -m "Update Kubernetes manifests for review environment"
    - git push gitlab_origin HEAD:${CI_COMMIT_REF_NAME} -o ci.skip
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://review-$CI_COMMIT_REF_SLUG.catweb.gitops.fun
    on_stop: review_destroy
  only:
    - merge_requests
  except:
    - branches



review_destroy:
  stage: review
  image:
    name: docker:latest
    entrypoint:
      - ""
  before_script:
    - apk add --no-cache git
    - git config --global user.email "adess@gitlab.com"
    - git config --global user.name
      "@project_44576698_bot_350adb3254374f09f5512b067abc866b"
  script:
    - cd manifests
    - git remote add gitlab_origin
      "https://oauth2:${CI_ACCESS_TOKEN}@gitlab.com/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}.git"
    - git rm review/$CI_COMMIT_REF_SLUG/k8s-deployment.yaml
    - git commit -m "Remove Kubernetes manifests for review environment"
    - git push gitlab_origin HEAD:main -o ci.skip
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  only:
    - merge_requests
  except:
    - branches
  when: manual
