stages:
  - build
  - gitops

# Build and push Docker image using Kaniko
build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE/main:$CI_COMMIT_SHA
  artifacts:
    paths:
      - updated-image-tag
    expire_in: 1 hour
  only:
    - main

# Commit Kubernetes manifests to the same repository
commit-manifests:
  stage: gitops
  image: 
    name: docker:latest
    entrypoint: [""]
  before_script:
    - apk add --no-cache curl git bash
    - curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
    - mv kustomize /usr/local/bin/
    - echo "registry.gitlab.com/adess-demos/demo/app-team/catweb-gitops/main:$CI_COMMIT_SHA" > updated-image-tag
  script:
    - cd manifests
    - sed -i "s|registry.gitlab.com/adess-demos/demo/app-team/catweb-gitops/main:latest|$(cat ../updated-image-tag)|g" deployment.yaml
    - kustomize build . > k8s-deployment.yaml
    - git add k8s-deployment.yaml
    - git commit -m "Update Kubernetes manifests with new image tag"
    - git push "https://oauth2:${CI_ACCESS_TOKEN}@gitlab.com/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}.git" HEAD:main
  only:
    - main
