apiVersion: apps/v1
kind: Deployment
metadata:
  name: catweb-go
spec:
  selector:
    matchLabels:
      app: catweb
  replicas: 3
  template:
    metadata:
      labels:
        app: catweb
    spec:
      containers:
      - name: catweb
        image: registry.gitlab.com/adess-demos/demo2win/catweb/master:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
