apiVersion: apps/v1
kind: Deployment
metadata:
  name: catweb-go
spec:
  selector:
    matchLabels:
      app: catweb
  replicas: 1
  template:
    metadata:
      labels:
        app: catweb
    spec:
      containers:
      - name: catweb
        image: pvdbleek/catweb-go
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: catweb
  labels:
    app: catweb
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32080
  selector:
    app: catweb
