apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: catweb-go
spec:
  selector:
    matchLabels:
      app: catweb
  replicas: 6
  template:
    metadata:
      labels:
        app: catweb
    spec:
      containers:
      - name: catweb
        image: dtr.pvdbleek.dtcntr.net/pvdbleek/catweb-go:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: catweb
  labels:
    app: catweb
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 33080
  selector:
    app: catweb
