version: '3.2'

services:

  nogcatweb-go:
    image: dtr.pvdbleek.dtcntr.net/prod/catweb-go:latest
    ports:
      - 8080:8080
    deploy:
      replicas: 6
      labels:
        com.docker.lb.hosts: catweb.pvdbleek.dtcntr.net
        com.docker.lb.network: ucp-interlock
        com.docker.lb.port: 8080
    networks:
      - ucp-interlock

networks:
  ucp-interlock:
    external: true
