apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7InVzZXJuYW1lIjoicHJvamVjdF80NDU3NjY5OF9ib3RfM2EzZjY4N2VlMTkzMTNmMzRjNzllMzU4NjE3NWVhYmUiLCJwYXNzd29yZCI6ImdscGF0LUp2ZURoUzdVdnZBLXV3dHBFTGY0IiwiYXV0aCI6ImNISnZhbVZqZEY4ME5EVTNOalk1T0Y5aWIzUmZNMkV6WmpZNE4yVmxNVGt6TVRObU16UmpOemxsTXpVNE5qRTNOV1ZoWW1VNloyeHdZWFF0U25abFJHaFROMVYyZGtFdGRYZDBjRVZNWmpRPSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: gitlab-registry-credentials
  namespace: prod
type: kubernetes.io/dockerconfigjson