apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: catweb
  namespace: prod
spec:
  tls:
  - hosts:
    - review-${CI_COMMIT_REF_SLUG}.catweb.gitops.fun
    secretName: catweb-tls
  rules:
  - host: review-${CI_COMMIT_REF_SLUG}.catweb.gitops.fun
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: catweb
            port:
              number: 80