apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: registry.gitlab.com/adess-demos/demo/app-team/catweb-gitops/main:24f2b3b9db21ccbab7b338ba0242d3fc44100253
        name: my-app
        ports:
        - containerPort: 80
