apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- catweb-ingress.yaml

patchesStrategicMerge:
- image-pull-secrets-patch.yaml

images:
- name: registry.gitlab.com/adess-demos/demo/app-team/catweb-gitops
  newName: registry.gitlab.com/adess-demos/demo/app-team/catweb-gitops:registry.gitlab.com/adess-demos/demo/app-team/catweb-gitops/main
  newTag: 10e88e97b8a89727c8f3d1789924619d60d1e639
