apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

patchesStrategicMerge:
- image-pull-secrets-patch.yaml

images:
- name: registry.gitlab.com/adess-demos/demo/app-team/catweb-gitops
  newName: registry.gitlab.com/adess-demos/demo/app-team/catweb-gitops:registry.gitlab.com/adess-demos/demo/app-team/catweb-gitops/main
  newTag: 071c34056ee59c03e2de6270c8adc14070b948b4
