apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

patchesStrategicMerge:
- image-pull-secrets-patch.yaml

images:
  - name: registry.gitlab.com/adess-demos/demo/app-team/catweb-gitops
    newName: registry.gitlab.com/adess-demos/demo/app-team/catweb-gitops
    newTag: latest
