apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- catweb-ingress.yaml
- image-pull-secret.yaml

patches:
- path: image-pull-secrets-patch.yaml
images:
- name: registry.gitlab.com/adess-demos/demo/app-team/catweb-gitops
  newName: registry.gitlab.com/adess-demos/demo/app-team/catweb-gitops:registry.gitlab.com/adess-demos/demo/app-team/catweb-gitops/main
  newTag: 4cb5051f0fbbfcaa40bb9a04a8bc66dfe1b89579
namespace: prod
