apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- catweb-ingress.yaml
- image-pull-secret.yaml

patches:
- path: image-pull-secrets-patch.yaml
images:
- name: registry.gitlab.com/adess-demos/demo/app-team/catweb-gitops
  newName: registry.gitlab.com/adess-demos/demo/app-team/catweb-gitops:registry.gitlab.com/adess-demos/demo/app-team/catweb-gitops/main
  newTag: c24e9cfa82d10836e8705e9ce7168be4b7e5ad8f
namespace: review-17-enable-sast-scanning
